report:
	latexmk report.tex

report-dev:
	latexmk -pvc report

proposal:
	latexmk proposal.tex

proposal-dev:
	latexmk -pvc proposal

clean:
	latexmk -C
	-rm *.lol
	-rm *.bbl
	-rm *.run.xml
	-rm -r _minted*
	-rm *.nav
	-rm *.pyg
	-rm *.snm
	-rm *.vrb
	-rm *.fls
