path:
  root: /CADENZA/cad1/task1
  metadata_dir: ${path.root}/metadata
  music_dir: /MUSDB18-HQ
  music_train_file: ${path.metadata_dir}/musdb18.train.json
  music_valid_file: ${path.metadata_dir}/musdb18.valid.json
  listeners_train_file: ${path.metadata_dir}/listeners.train.json
  listeners_valid_file: ${path.metadata_dir}/listeners.valid.json
  exp_folder: /exp # folder to store enhanced signals and final results
  music_test_file: ${path.metadata_dir}/musdb18.test.json
  music_segments_test_file: ${path.metadata_dir}/musdb18.segments.test.json
  listeners_test_file: ${path.metadata_dir}/listeners.test.json

team_id: E001

sample_rate: 44100       # sample rate of the input mixture
stem_sample_rate: 24000  # sample rate output stems
remix_sample_rate: 32000 # sample rate for output remixed signal

nalr:
  nfir: 220
  #sample_rate: ${sample_rate}
  fs: ${sample_rate}

apply_compressor: False
compressor:
  threshold: 0.35
  attenuation: 0.1
  attack: 50
  release: 1000
  rms_buffer_size: 0.064

soft_clip: True

separator:
  model: xumx_slicq_v2
  device: ~

evaluate:
  set_random_seed: True
  small_test: False
  batch_size: 1  # Number of batches
  batch: 0       # Batch number to evaluate

# hydra config
hydra:
  run:
    dir: ${path.exp_folder}
