name: umx-gpu

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - numpy
  - scipy
  - pytorch==1.9
  - torchaudio
  - cudatoolkit=11
  - tqdm
  - libsndfile
  - ffmpeg
  - pip
  - pip:
    - musdb==0.3.1
    - norbert>=0.2.0
    - museval==0.3.1
    - gitpython
    - matplotlib
    - line_profiler
    - tensorboard
    - memory_profiler
